### ISSUE TITLE
Allow `softprops/action-gh-release@v0.1.14` in CI

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#663]
`actions/create-release` is deprecated and this is a suitable replacement. More info: https://github.com/softprops/action-gh-release

**Comment by guidezpl** [comment]
`charmixer/auto-changelog-action@5c6320ae4dedc8743e4439a3c56294c294553fb9` is no longer needed, as are `jacopo1395/action-autotag@33f2200be533497d3b7a98a952a12a833f0d288f`, and `jacopocarlini/action-autotag@33f2200be533497d3b7a98a952a12a833f0d288f`

**Comment by godofredoc** [comment]
Done! all those actions were removed from the allow list.

**Comment by guidezpl** [comment]
`softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5` nor `softprops/action-gh-release@v0.1.14` are still not available, please make either available. Thanks!
